theme: minima

title: "Shazad Ahmed"
description: "Data Analytics & Business Intelligence Leader | Epidemiologist"

author:
  name: "Shazad Ahmed"
  bio: "Data Analytics & Business Intelligence Leader"
  location: "United States"
