theme: minima
title: Shazad Ahmed's GitHub portfolio homepage
description: Data Analytics & Business Intellgence Leader | Epidemiologist 
This webpage showcases some of my data projects and sample scripts

