theme: minimal
title: "Shazad Ahmed's GitHub Portfolio"
description: "Data Analytics & Business Intelligence Leader | Epidemiologist"
tagline: "This webpage showcases some of my data projects and sample scripts"
